spring:
  kafka:
    streams:
      application-id: alert-manager
      bootstrap-servers: localhost:9092
  profiles:
    active: @active.profile@

alert-manager:
  alerts-topic:
    name: alerts
    partitions: 3
    replicas: 0
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

---

spring:
  config:
    activate:
      on-profile: h2

---
spring:
  config:
    activate:
      on-profile: postegrsql
  datasource:
    hikari:
      jdbc-url:
      username:
      password:


